### ISSUE TITLE
not sure it is an issue, but i can not serialize inherited class

### ISSUE THREAD

**Issue by jerome-diver** [jl2922/hps#24]
Code is compiling, but at run time, it crash with error:
terminate called after throwing an instance of "std::logic_error"
 what(): Serializer not found for type 1A
(abort core dumped)

my testcase codes:
[main.cpp](https://ptpb.pw/0Pqb)
[object.h](https://ptpb.pw/spwR)
[object.cpp](https://ptpb.pw/-Iyk)

So, not sure it is an issue, it try to understand how i should use serialization from hps fr inherited class, but maybe i failed to understand well.

**Comment by jl2922** [comment]
The order of the template class seems to be wrong. T shall be the second
parameter in:

class Serializer<T, datas>


Junhao Li
Cornell University |
​
Physics

**Comment by jerome-diver** [comment]
Yes, that was the problem.
Now it works fine. I understand how it works now.
Thank you very much for your help, i go ahead on some test case situations and should use it for my C++ code about server/client TCP communication.
There is no issue at all.
