### ISSUE TITLE
How to access ancestor private/protected local variables ?

### ISSUE THREAD

**Issue by jerome-diver** [jl2922/hps#25]
Hi again,
I'm searching how to implement class template Serializer for embed private/protected local variable from an ancestor class ?
If i have an abstract ancestor parent class of an other one who has private variables, i not find how to access these variable for serialize/parse.
Could you provide a little example of code for i can learn how to do that with hps please ?
(happy new year also)

[object.h](https://ptpb.pw/zPW_)

From boost serialize example, i see it is possible to implement class objects (intrusive method) for archive private methods. So maybe there is a way in the same intrusive code methods with hps... but i actuallt failed by use friend class hps::Serializer then implement class inside other class...

**Comment by jl2922** [comment]
It is actually pretty easy. You can either declare the Serializer<...> as a
friend class, or use getters and setters in the serialize and parse methods
of the Serializer.

**Comment by jerome-diver** [comment]
It is actually what i'm trying to do... but i failed.
This is an example about what 'im trying to do for follow the way you was talking about:
[object.h](https://ptpb.pw/IJYv)

could you; please, provide a correct example from there about:

1. how to have a valid friend class of hps::Serializer<MyClass, ??>; 
2. and how to overload methods ?

**Comment by jerome-diver** [comment]
Ok, someone helped me on irc freenode ##c++-general channel and now i learned how to be friend with namespace nested class for many typenames...
just add this:
```
template<typename X, typename Y>
friend class hps::Serializer;
``` 
and i also arrived with getters and setters, but it is much more boring and intrusive than just be friend this way.

inside each class who has private variables to be access from Serializer methods... et voilà !
Not to much intrusive finally... a little bit.
thank you for hps library and your help
I like this library.
(maybe possible to add example for this ability, i know good C++ devs not need, but for little guys like me, it should be fun...)

**Comment by jl2922** [comment]
Yep, glad you like it.

**Comment by jl2922** [comment]
I just updated the README to show how to delegate serialization to the custom class itself, so there will be no more private member issues. In my opinion, this is probably a clearer structure for most cases.
