### ISSUE TITLE
serialize a unordered_map<int, unordered_map<int, string> > to a file and deserialize it back. 

### ISSUE THREAD

**Issue by Ragu9967** [jl2922/hps#41]
hi, i have initialized a unordered_map<int, unordered_map<int, string> > and i have inserted values into it. now from the examples given i can write it to a file using 'to_stream()' like this...
    std::ofstream out_file("data.log", std::ofstream::binary);  //lets say data.log is the filename
    hps::to_stream(data, out_file);
Now how can reconstruct the map from this file stream ???? 
I would be really great if you could help me with this one.
Thanks

**Comment by jl2922** [comment]
You can just follow the example and replace vector with your type. Is that not working for you?

**Comment by Ragu9967** [comment]
hi @jl2922 , okay thank you. i guess i did some mistake previously. and i have few questions,
1. what does that assert() function does??
2. does this library has any performance issues after reaching n number of entries to any stl containers ?

**Comment by Ragu9967** [comment]
i can serialize/deserialize the stl containers but for the example code i tried, for serializing it took around 2 sec. but for deserializing it took around 8.5 sec. Is there any way we can improve the deserializing time ? 
Thanks.

**Comment by jl2922** [comment]
1. assert ensures you get back the original object after you deserialize.

2. the only issue comes from the allocation of the stl containers. I guess if you construct a similar size container using some arbitrary numbers, it will also take around 8 sec.

**Comment by jl2922** [comment]
You may use the tcmalloc from Google to speed up the memory allocation, at the price of slightly more frequent server failures.
