### ISSUE TITLE
from_char_array bug?

### ISSUE THREAD

**Issue by mipac** [jl2922/hps#42]
I can deserialize int member of a structure from a char array, but not double member (equals to 0)

If I convert the char buffer to string and then use from_string, it works!

**Comment by jl2922** [comment]
Do you have an simple example for reproducing the error?

**Comment by evd0kim** [comment]
I have the same bug.

**Comment by evd0kim** [comment]
```
        std::vector<double> ddata({101325, 101326, 101327});
        std::string dserialized = hps::to_string(ddata);
        auto dparsed = hps::from_string<std::vector<double>>(dserialized);
        assert(dparsed == ddata);
        auto cparsed = hps::from_char_array<std::vector<double>>(dserialized.c_str());
        assert(cparsed == ddata);
  ```
  
Assertion `cparsed == ddata' failed.

**Comment by evd0kim** [comment]
Seemingly working solution is to use std::copy. It doesn't copy zero bytes.

https://github.com/engenegr/hps/blob/22509b63fd2346aca5e7b90af707ae16e5e8e23b/src/buffer/char_array_input_buffer.h#L16

It is my temporary bugfix, I suppose it may be solved on slightly different way closer to original strncpy.

**Comment by evd0kim** [comment]
I generally moved activity here and developed some additional tests

https://github.com/engenegr/hps/

they are failing. std::copy only makes situation slightly better since I discovered errors in conversion in my software and some situations when tests are failing.

**Comment by evd0kim** [comment]
Custom types may be also failing.

USE THIS LIBRARY CAREFULLY
