### ISSUE TITLE
any hint on how I can use hps for python numpy array?

### ISSUE THREAD

**Issue by kingsrd** [jl2922/hps#45]
is there any chance we can add support for python numpy array (which is actually implemented in c)? or any hints on how to do that would be much appreciated,

**Comment by jl2922** [comment]
Currently I don't have time to look into that. I would suggest looking into the python doc to see whether there is some easy way to create a python module from c++, and then write a specialization (polymorphism) for numpy array. If it is a floating point numpy array, the serialized version is just the 128-base encoding of the length plus numpy.ndarray.tobytes(arr).

**Comment by kingsrd** [comment]
@jl2922 thanks for the reply, I thought the data being serialized will have to be a native c++ std container i.e. I would have to do a 1-2-1 mapping of numpy.ndarry to e.g. std:vector? but it sounds like hps can work on an arbitrary chunk of bytes? if this is the case, how does it detect if that data is sparse or dense?

**Comment by jl2922** [comment]
You can always extend hps to support new types, just like what I did to support C++ primitive types and STL containers, and as you mentioned you may reuse some methods for std:vector when doing that. Hps doesn't detect the original type of the binary data, but instead relied on the type of the input and the template argument.
